# Generated by Django 3.2.9 on 2021-11-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211112_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as an Preview Employee. ', verbose_name='Preview Employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'أدمن'), (2, 'مدير تنفيذى'), (3, 'محاسب'), (4, 'مقيم'), (5, 'مدخل بيانات'), (5, 'معاين ')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
