# Generated by Django 3.2.9 on 2021-11-12 12:55

from django.db import migrations, models
import django.db.models.deletion
import office.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('authorizations', models.TextField(blank=True, null=True)),
                ('rights', models.TextField(blank=True, null=True)),
                ('benfits', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.CharField(default=office.models.Documents.DocumentNumber, max_length=255, unique=True)),
                ('ownerPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('ownerName', models.CharField(blank=True, max_length=255, null=True)),
                ('ownerNationalID', models.CharField(max_length=255, null=True, unique=True)),
                ('realStateType', models.SmallIntegerField(choices=[(1, 'فيلا'), (2, 'أرض'), (3, 'مخطط'), (4, 'عمارة سكنية'), (5, 'عمارة مكتبة'), (6, 'مجالات '), (7, 'مصنع'), (8, 'مكتب')])),
                ('paperNumber', models.IntegerField(blank=True, null=True)),
                ('paperDate', models.DateField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('buildingArea', models.IntegerField(blank=True, null=True)),
                ('ratingPurpose', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.clients')),
            ],
        ),
    ]
