# Generated by Django 3.2.9 on 2021-11-12 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='dateEntered',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 11, 12, 19, 38, 50, 555175)),
        ),
        migrations.AddField(
            model_name='documents',
            name='enteredBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
