# Generated by Django 3.2.9 on 2021-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_documents_dateentered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='dateEntered',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
