# Generated by Django 3.2.9 on 2021-11-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_rename_locationurl_preview_locationurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='realStateType',
            field=models.SmallIntegerField(choices=[(1, 'فيلا'), (2, 'أرض'), (3, 'مخطط'), (4, 'عمارة سكنية'), (5, 'عمارة مكتبة'), (6, 'مجالات '), (7, 'مصنع'), (8, 'مكتب')], null=True),
        ),
    ]
