# Generated by Django 3.2.9 on 2021-12-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_documents_realstatetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.clients'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='realStateType',
            field=models.SmallIntegerField(choices=[(1, 'فيلا'), (2, 'أرض'), (3, 'مخطط'), (4, 'عمارة سكنية'), (5, 'عمارة مكتبة'), (6, 'معرض '), (7, 'مصنع'), (8, 'مكتب')], null=True),
        ),
    ]
