# Generated by Django 3.0 on 2022-01-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20220109_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='clients_documents/'),
        ),
        migrations.AddField(
            model_name='clients',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='clients_documents/'),
        ),
        migrations.AddField(
            model_name='clients',
            name='document_3',
            field=models.FileField(blank=True, null=True, upload_to='clients_documents/'),
        ),
    ]
