# Generated by Django 3.0 on 2022-01-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_auto_20220131_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
