# Generated by Django 3.0 on 2022-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_documents_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
