# Generated by Django 3.0 on 2022-02-01 16:12

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_preview_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='documents',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='ownerName'),
        ),
        migrations.AddField(
            model_name='preview',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='locationDescription'),
        ),
    ]
