# Generated by Django 3.0 on 2022-02-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_auto_20220201_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='office.Documents'),
        ),
    ]
