# Generated by Django 3.2.9 on 2021-12-10 22:50

import accountant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherId', models.CharField(default=accountant.models.Voucher.VoucherNumber, max_length=255, unique=True)),
                ('voucherDate', models.DateTimeField(auto_now_add=True)),
                ('taxCompanyNumber', models.IntegerField(blank=True, null=True)),
                ('recordId', models.IntegerField(unique=True)),
                ('companyAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('payMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('clientName', models.CharField(blank=True, max_length=255, null=True)),
                ('clientPhone', models.CharField(blank=True, max_length=255, null=True)),
                ('clientAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('clientTaxNumber', models.IntegerField(blank=True, null=True)),
                ('taxRatio', models.SmallIntegerField(blank=True, null=True)),
                ('totalBeforeTax', models.IntegerField(blank=True, null=True)),
                ('voucherCode', models.CharField(blank=True, max_length=255, null=True)),
                ('voucherDescription', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
