# Generated by Django 3.0 on 2022-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_auto_20220109_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/qrcode'),
        ),
    ]
