# Generated by Django 3.0 on 2022-02-01 16:12

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_voucher_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='clientName'),
        ),
    ]
