# Generated by Django 3.2.9 on 2021-11-26 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0007_alter_documents_realstatetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residentRate', models.CharField(blank=True, max_length=255, null=True)),
                ('valueBase', models.SmallIntegerField(blank=True, choices=[(1, 'عادله'), (2, 'تصفية'), (3, 'سوقية'), (4, 'بيع قصرى'), (5, 'احادية')], null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.documents')),
            ],
        ),
    ]
