# Generated by Django 3.2.9 on 2021-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_auto_20211127_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparebuilding',
            name='areaPrecentage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparebuilding',
            name='locationPrecentage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparebuilding',
            name='streetPrecentage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparebuilding',
            name='usagePrecentage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparebuilding',
            name='zonePrecentage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
