# Generated by Django 3.2.9 on 2021-11-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0004_auto_20211127_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentbuilding',
            name='document',
        ),
        migrations.AddField(
            model_name='residentbuilding',
            name='residentDocument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comparison.residentdocument'),
        ),
    ]
