# Generated by Django 3.2.9 on 2021-11-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_documents_realstatetype'),
        ('comparison', '0005_auto_20211127_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentbuilding',
            name='residentDocument',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comparison.residentdocument'),
        ),
        migrations.AlterField(
            model_name='residentdocument',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.documents'),
        ),
    ]
