# Generated by Django 3.2.9 on 2021-12-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0006_auto_20211127_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndirectBuildingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicalFees', models.IntegerField(blank=True, null=True)),
                ('developerFees', models.IntegerField(blank=True, null=True)),
                ('serviceFees', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.residentdocument')),
            ],
        ),
        migrations.CreateModel(
            name='DirectBuildingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaBuildCost', models.IntegerField(blank=True, null=True)),
                ('priceMeterCost', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.residentdocument')),
            ],
        ),
    ]
