# Generated by Django 3.2.9 on 2021-12-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0007_directbuildingcost_undirectbuildingcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directbuildingcost',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.residentdocument', unique=True),
        ),
        migrations.AlterField(
            model_name='undirectbuildingcost',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.residentdocument', unique=True),
        ),
        migrations.CreateModel(
            name='DamagedBuildingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingAge', models.IntegerField(blank=True, null=True)),
                ('normalAge', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.residentdocument', unique=True)),
            ],
        ),
    ]
