# Generated by Django 3.0 on 2022-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0009_auto_20220109_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentdocument',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
