from django.urls import path
from . import views

urlpatterns = [
    path('update/direct/<int:pk>',
         views.UpdateDirectCost.as_view(), name='update-direct'),
    path('update/undirect/<int:pk>',
         views.UpdateUnDirectCost.as_view(), name='update-undirect'),
    path('update/damaged/<int:pk>',
         views.UpdateDamaged.as_view(), name='update-damaged'),
    path('DirectCompare/<int:pk>',
         views.DirectAndUnDirectPage.as_view(), name='direct-compare'),
    path('DamagedCompare/<int:pk>',
         views.DamagedPage.as_view(), name='damaged-compare'),
    path('SouqCompare/<int:pk>',
         views.SouqComparePage.as_view(), name='souq-compare'),
    path('direct/add', views.AddDirectCost.as_view(),
         name='add-direct'),
    path('damaged/add', views.AddDamaged.as_view(),
         name='add-damaged'),
    path('undirect/add', views.AddUnDirectCost.as_view(),
         name='add-undirect'),
    path('residentDocument/update/<int:pk>',
         views.UpdateResidentDocument.as_view(), name='update-residentDocument'),
    path('residentDocument/add/<int:pk>', views.AddResidentDocument.as_view(),
         name='add-residentDocument'),
    path('compareDocument/add', views.AddCompareBuilding.as_view(),
         name='add-compareDocument'),
    path('compareDocument/update/<int:pk>',
         views.UpdateCompareBuilding.as_view(), name='update-compareDocument'),
    path('residentBuilding/add', views.AddResidentBuilding.as_view(),
         name='add-residentBuilding'),
    path('residentBuilding/update/<int:pk>',
         views.UpdateResidentBuilding.as_view(), name='update-residentBuilding'),
    path('complete/resident/<int:pk>',
         views.SetResidentCompleted, name='set_resident_complete'),

]
